Feature/user create
Turnmed/turnmed-server pull request #3
Opened 2022-08-22 18:48 UTC by FacundoBocalandro

https://trello.com/c/w1Xz3CWb/40-be-alta-usuarios

2022-08-24 23:15 UTC, EliasLeonov requested changes

2022-08-24 23:15 UTC, EliasLeonov commented on prisma/schema.prisma
> +  female
Añadir la opcion de "not_informed"

2022-08-25 14:02 UTC, matiaslcoulougian commented on prisma/schema.prisma
> +  female
Done!

2022-08-25 14:05 UTC, EliasLeonov approved these changes

2022-08-25 14:05 UTC, merged